version: 0.0
os: linux

files:
  - source: dist/
    destination: /var/www/html
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/install_apache.sh
      runas: root

  ApplicationStart:
    - location: scripts/start_apache.sh
      runas: root
