version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/install_apache.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/permissions.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_apache.sh
      timeout: 300
      runas: root
