version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - npm install

  build:
    commands:
      - echo "Building Vite React application"
      - npm run build

  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - dist/**/*
    - appspec.yml
    - scripts/**/*